# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
    adapter: mysql2
    encoding: utf8
    reconnect: true
    database: blog
    pool: 5
    username: root
    password: q1w2e3r4
    socket: /tmp/mysql.sock

test:
    adapter: mysql2
    encoding: utf8
    reconnect: true
    database: blog
    pool: 5
    username: root
    password: q1w2e3r4
    socket: /tmp/mysql.sock
  
production:
    adapter: mysql2
    encoding: utf8
    reconnect: true
    database: blog
    pool: 5
    username: root
    password: q1w2e3r4
    socket: /tmp/mysql.sock